require "test_helper"

class Rails::Metro::TemplateCompilerTest < Minitest::Test
  def test_compile_header
    compiler = build_compiler([])
    output = compiler.compile
    assert_match(/Generated by rails-metro/, output)
  end

  def test_compile_with_no_packs
    compiler = build_compiler([])
    output = compiler.compile
    refute_match(/gem /, output)
    refute_match(/after_bundle/, output)
  end

  def test_compile_includes_gems
    compiler = build_compiler([Rails::Metro::Packs::ChartingPack])
    output = compiler.compile
    assert_match(/gem "chartkick"/, output)
    assert_match(/gem "groupdate"/, output)
  end

  def test_compile_includes_after_bundle
    compiler = build_compiler([Rails::Metro::Packs::BlazerPack])
    output = compiler.compile
    assert_match(/after_bundle do/, output)
    assert_match(/blazer:install/, output)
  end

  def test_compile_multiple_packs
    compiler = build_compiler([
      Rails::Metro::Packs::PosthogPack,
      Rails::Metro::Packs::BlazerPack,
      Rails::Metro::Packs::ChartingPack
    ])
    output = compiler.compile
    assert_match(/posthog-ruby/, output)
    assert_match(/blazer/, output)
    assert_match(/chartkick/, output)
  end

  def test_compile_to_file_creates_tempfile
    compiler = build_compiler([Rails::Metro::Packs::PosthogPack])
    path = compiler.compile_to_file
    assert File.exist?(path)
    content = File.read(path)
    assert_match(/posthog-ruby/, content)
  ensure
    File.unlink(path) if path && File.exist?(path)
  end

  def test_compile_deterministic
    compiler = build_compiler([Rails::Metro::Packs::PosthogPack, Rails::Metro::Packs::BlazerPack])
    output1 = compiler.compile
    output2 = compiler.compile
    assert_equal output1, output2
  end

  def test_post_install_notes
    compiler = build_compiler([Rails::Metro::Packs::PosthogPack])
    notes = compiler.post_install_notes
    assert notes.any? { |n| n.include?("PostHog") }
  end

  def test_grouped_gems
    compiler = build_compiler([Rails::Metro::Packs::TestingPack])
    output = compiler.compile
    assert_match(/gem_group :test do/, output)
    assert_match(/factory_bot_rails/, output)
  end

  private

  def build_compiler(pack_classes)
    config = Rails::Metro::Config.new(app_name: "testapp")
    Rails::Metro::TemplateCompiler.new(config: config, packs: pack_classes)
  end
end
