# Generated by rails-metro v0.1.0
# Packs: graphql, api_cors, doorkeeper, api_serialization
#
# Apply with: rails new APP_NAME -m this_template.rb
# Or: bin/rails app:template LOCATION=this_template.rb

gem "graphql", "~> 2.0"
gem "rack-cors"
gem "doorkeeper"
gem "alba", "~> 3.0"


after_bundle do
  rails_command "generate graphql:install"
  create_file "config/initializers/cors.rb", <<~RUBY
    Rails.application.config.middleware.insert_before 0, Rack::Cors do
      allow do
        origins Rails.application.credentials.dig(:cors, :origins) || ENV.fetch("CORS_ORIGINS", "http://localhost:3000")
  
        resource "*",
          headers: :any,
          methods: %i[get post put patch delete options head],
          credentials: true
      end
    end
  RUBY
  rails_command "generate doorkeeper:install"
  rails_command "generate doorkeeper:migration"
  create_file "config/initializers/alba.rb", <<~RUBY
    Alba.backend = :oj
  RUBY
  
  create_file "app/resources/application_resource.rb", <<~RUBY
    class ApplicationResource
      include Alba::Resource
    end
  RUBY
end