# Generated by rails-metro v0.1.0
# Packs: authentication, posthog, background_jobs, deployment
#
# Apply with: rails new APP_NAME -m this_template.rb
# Or: bin/rails app:template LOCATION=this_template.rb

gem "authentication-zero"
gem "posthog-ruby"
gem "posthog-rails"
gem "solid_queue"
gem "mission_control-jobs"
gem "kamal", "~> 2.0"


after_bundle do
  rails_command "generate authentication"
  create_file "config/initializers/posthog.rb", <<~RUBY
    PostHog.init do |config|
      config.api_key = ::Rails.application.credentials.dig(:posthog, :api_key) || ENV["POSTHOG_API_KEY"] || "phc_your_key_here"
      config.host = ::Rails.application.credentials.dig(:posthog, :host) || "https://us.i.posthog.com"
      config.on_error = proc { |status, msg| ::Rails.logger.error("[PostHog] \#{status}: \#{msg}") }
    end
  RUBY
  rails_command "solid_queue:install"
  route "mount MissionControl::Jobs::Engine, at: \"/jobs\""
  rails_command "generate kamal"
end