require "tempfile"

module Rails
  module Metro
    class TemplateCompiler
      attr_reader :config, :packs

      def initialize(config:, packs:)
        @config = config
        @packs = packs
      end

      def compile
        lines = []
        lines << header
        lines << ""
        lines << gem_declarations
        lines << ""
        lines << after_bundle_block
        lines.flatten.join("\n")
      end

      def compile_to_file
        content = compile
        tmpfile = Tempfile.new(["rails-metro-template", ".rb"])
        tmpfile.write(content)
        tmpfile.close
        tmpfile.path
      end

      def post_install_notes
        packs.flat_map { |p| p.new.post_install_notes }.compact
      end

      private

      def header
        pack_names = packs.map(&:pack_name).join(", ")
        [
          "# Generated by rails-metro v#{VERSION}",
          "# Packs: #{pack_names}",
          "#",
          "# Apply with: rails new APP_NAME -m this_template.rb",
          "# Or: bin/rails app:template LOCATION=this_template.rb"
        ]
      end

      def gem_declarations
        all_gems = packs.flat_map { |p| p.new.gems }.uniq { |g| g[:name] }
        return [] if all_gems.empty?

        grouped = all_gems.group_by { |g| g[:group] }
        lines = []

        ungrouped = grouped.delete(nil) || []
        ungrouped.each do |g|
          version = g[:version] ? ", \"#{g[:version]}\"" : ""
          lines << "gem \"#{g[:name]}\"#{version}"
        end

        grouped.each do |group, gems|
          lines << ""
          lines << "gem_group :#{group} do"
          gems.each do |g|
            version = g[:version] ? ", \"#{g[:version]}\"" : ""
            lines << "  gem \"#{g[:name]}\"#{version}"
          end
          lines << "end"
        end

        lines
      end

      def after_bundle_block
        template_lines = packs.flat_map { |p| p.new.template_lines }
        return [] if template_lines.empty?

        lines = ["", "after_bundle do"]
        template_lines.each { |line| lines << "  #{line}" }
        lines << "end"
        lines
      end
    end
  end
end
